// AUTO-GENERATED by scripts/sync-airtable.mjs — do not edit by hand.
// Source: Airtable base appG5vyHr8qnwiaVU. Re-run: pnpm sync:airtable
// Generated: 2026-06-07T21:31:22.758Z
/* eslint-disable */

export type GeneratedVoucher = {
  voucher_address: `0x${string}`;
  symbol: string;
  voucher_name: string;
  voucher_description: string;
  voucher_type: "GIFTABLE";
  voucher_uoa: string;
  voucher_value: number;
  location_name: string;
  geo: { x: number; y: number };
  voucher_email: string | null;
  voucher_website: string | null;
  banner_url: string | null;
  icon_url: string | null;
  redemption_address: `0x${string}`;
  owner_name: string | null;
  owner_persona: string | null;
  category: string | null;
  created_at: string;
  transaction_count: number;
  internal: boolean;
  contract_version: string;
  airtable_id: string;
};

export const AIRTABLE_EFM_VOUCHERS: GeneratedVoucher[] = [
  {
    "voucher_address": "0x5c79dd28eb25d86753a6bff1942e36b9d7dbe63a",
    "symbol": "BH",
    "voucher_name": "Beyond Happiness",
    "voucher_description": "Handmade artisan soaps, candles, body oils & butters, incense and more",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "Easthampton Farmers Market, MA",
    "geo": {
      "x": 42.26573,
      "y": -72.67318
    },
    "voucher_email": "thesocialbreakthrough@gmail.com",
    "voucher_website": "https://linktr.ee/beyondhappiness",
    "banner_url": "https://619b00c56e4d8981e886.cdn6.editmysite.com/uploads/b/619b00c56e4d8981e8864791695f16befbf7269cbc55678743ea48a58f666a8e/PXL_20251012_201915377.RAW-01.COVER%20%283%29_1773846515.jpg?width=2400&optimize=medium",
    "icon_url": "https://619b00c56e4d8981e886.cdn6.editmysite.com/uploads/b/619b00c56e4d8981e8864791695f16befbf7269cbc55678743ea48a58f666a8e/PXL_20251012_201915377.RAW-01.COVER%20%283%29_1773846515.jpg?width=2400&optimize=medium",
    "redemption_address": "0xaa000000000000000000000000000000aa000001",
    "owner_name": "Aaron Andrews",
    "owner_persona": "alice",
    "category": "Soap & Body",
    "created_at": "2026-06-01",
    "transaction_count": 273,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "rec4O4YdfuRLAtdQe"
  },
  {
    "voucher_address": "0x83f5d9f2f34c40c4d562cb16630c5536024b874e",
    "symbol": "HEART",
    "voucher_name": "Hearth",
    "voucher_description": "Magical products for spaces and those who tend them.",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "Easthampton Farmers Market, MA",
    "geo": {
      "x": 42.26652,
      "y": -72.67789
    },
    "voucher_email": null,
    "voucher_website": "https://hearthecogoods.com/",
    "banner_url": "https://v5.airtableusercontent.com/v3/u/54/54/1780876800000/70Dvl7e-b2q4rsIlFtVKug/KfQNoH6VtGWgjYATx67B154PHStZ9-yo48CrBL3-RFIrOgjGmJk2JxhXh7bp2ayMMKSxHiuS-Mr4qFJ4eWxuTbixMCFeOXKmcplcCKdHmUveD6XQzxBpSyiZF5Eauq3ZEbRj8IQJFbTAi8YhqCFb8fskrDLS6_nGWMt0e6zb7EE/gkt83d9G7RcVDu97lQIFjFy21x37UwQgkNueoh6xtM0",
    "icon_url": "https://v5.airtableusercontent.com/v3/u/54/54/1780876800000/70Dvl7e-b2q4rsIlFtVKug/KfQNoH6VtGWgjYATx67B154PHStZ9-yo48CrBL3-RFIrOgjGmJk2JxhXh7bp2ayMMKSxHiuS-Mr4qFJ4eWxuTbixMCFeOXKmcplcCKdHmUveD6XQzxBpSyiZF5Eauq3ZEbRj8IQJFbTAi8YhqCFb8fskrDLS6_nGWMt0e6zb7EE/gkt83d9G7RcVDu97lQIFjFy21x37UwQgkNueoh6xtM0",
    "redemption_address": "0xbb000000000000000000000000000000bb000001",
    "owner_name": "Tara",
    "owner_persona": "bob",
    "category": "Cleaning Products",
    "created_at": "2026-06-01",
    "transaction_count": 231,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "recCLKgYfGr2QYn3C"
  },
  {
    "voucher_address": "0xa8017dc1391c720cd9f563efa166cbe1e11a5845",
    "symbol": "DNGF",
    "voucher_name": "Dave's Natural Garden Farm",
    "voucher_description": "A small, diverse farm producing vegetables, fruit, eggs, poultry, and a spectacular assortment of hanging baskets, houseplants, annuals, perennials, vegetable and herb starts for your home.",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "35 Amherst Street Granby, MA, 01033",
    "geo": {
      "x": 42.2518026,
      "y": -72.5425728
    },
    "voucher_email": "sales@davesnaturalgarden.com",
    "voucher_website": "https://davesnaturalgarden.com/",
    "banner_url": "https://davesnaturalgarden.com/wp-content/uploads/2022/06/Screen-Shot-2022-05-23-at-9.23.29-AM.png",
    "icon_url": "https://davesnaturalgarden.com/wp-content/uploads/2022/06/Screen-Shot-2022-05-23-at-9.23.29-AM.png",
    "redemption_address": "0xdd000000000000000000000000000000dd000001",
    "owner_name": "Dave & ",
    "owner_persona": "dave",
    "category": "Produce, Poultry, Eggs & Plants",
    "created_at": "2026-06-06",
    "transaction_count": 359,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "recFpgY3EJC7ZcZvV"
  },
  {
    "voucher_address": "0xc3bba0a8314a84b0c7d95ebd9f714aab3d1a2b69",
    "symbol": "SBL",
    "voucher_name": "Sweetly By Leila",
    "voucher_description": "At Sweetly by Leila, cake is more than dessert‚Äîit's about connection, celebration, and creating memories. Every creation reflects uniqueness, joy, and the belief that life's moments, big and small, deserve to be celebrated.",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "Easthampton, MA",
    "geo": {
      "x": 42.2708804,
      "y": -72.6719579
    },
    "voucher_email": "sweetly.byleila@gmail.com",
    "voucher_website": "https://www.sweetlybyleila.com/",
    "banner_url": "https://static.wixstatic.com/media/d1bc48_2f91000d216a49c694dbeffb39cac652~mv2.jpg/v1/fill/w_857,h_1024,al_c,q_85,enc_avif,quality_auto/d1bc48_2f91000d216a49c694dbeffb39cac652~mv2.jpg",
    "icon_url": "https://static.wixstatic.com/media/d1bc48_2f91000d216a49c694dbeffb39cac652~mv2.jpg/v1/fill/w_857,h_1024,al_c,q_85,enc_avif,quality_auto/d1bc48_2f91000d216a49c694dbeffb39cac652~mv2.jpg",
    "redemption_address": "0xcc000000000000000000000000000000cc000001",
    "owner_name": "Leila",
    "owner_persona": "carol",
    "category": "Cakes",
    "created_at": "2026-06-01",
    "transaction_count": 107,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "recNVeRxPEH7tspd5"
  },
  {
    "voucher_address": "0xc542c74562819c35961b41492029773552d31ff6",
    "symbol": "SGP",
    "voucher_name": "Sid's Gumbo Pot",
    "voucher_description": "Cajun & Creole Cuisine.",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "Easthampton Farmers Market, MA",
    "geo": {
      "x": 42.27289,
      "y": -72.6793
    },
    "voucher_email": "sidsgumbopot@gmail.com",
    "voucher_website": null,
    "banner_url": "https://v5.airtableusercontent.com/v3/u/54/54/1780876800000/jUdafcdimWdhoULwQgGEjw/JWhKIp6zwpppPEOxExJLtI2QxbSD9AkRBmj1nVD8dqGr7HauEqDzkTtqUfIc4OHySAFw7VLohNvXD3lBdh0ABNWuhaYhdbW22TPJW4POrdP4ynZ0kX5uq5BiNYLYOyuwwEhLAU2BsX5MNsAwJEwmBjr3QbsOPH9akqbvCgBqnbs/nX22Nz3A6D3r5UjlVZOsWHi0npSkOXYhAs2a-oJFUxY",
    "icon_url": "https://v5.airtableusercontent.com/v3/u/54/54/1780876800000/jUdafcdimWdhoULwQgGEjw/JWhKIp6zwpppPEOxExJLtI2QxbSD9AkRBmj1nVD8dqGr7HauEqDzkTtqUfIc4OHySAFw7VLohNvXD3lBdh0ABNWuhaYhdbW22TPJW4POrdP4ynZ0kX5uq5BiNYLYOyuwwEhLAU2BsX5MNsAwJEwmBjr3QbsOPH9akqbvCgBqnbs/nX22Nz3A6D3r5UjlVZOsWHi0npSkOXYhAs2a-oJFUxY",
    "redemption_address": "0x80fe24c7475cee4ef65aff75c921e53cbee58a26",
    "owner_name": "Sid Cavallo",
    "owner_persona": null,
    "category": "Gumbo and Cajun Food",
    "created_at": "2026-06-06",
    "transaction_count": 148,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "recTnVCTyTCVeIAOW"
  },
  {
    "voucher_address": "0x314decfef49f87d5fee4ca2e53f9177cabf7fa5c",
    "symbol": "UF",
    "voucher_name": "Underline Farm",
    "voucher_description": "Underline Farm is a small-scale regenerative farm in Easthampton, Massachusetts producing pasture-raised chickens using organic methods. Our products are available at local farm stores, fine butchers and farmers markets.",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "P.O. Box 413, Easthampton, MA 01027",
    "geo": {
      "x": 42.26791,
      "y": -72.66506
    },
    "voucher_email": "underlinefarm@gmail.com",
    "voucher_website": "www.underlinefarm.com",
    "banner_url": "https://www.underlinefarm.com/gallery?pgid=jjz2uhq6-37ef36ad-a7f6-4b36-abcc-f37d20ae8643",
    "icon_url": "https://www.underlinefarm.com/gallery?pgid=jjz2uhq6-37ef36ad-a7f6-4b36-abcc-f37d20ae8643",
    "redemption_address": "0x4614327d1afbef4018110e22d7c8d54e686b9792",
    "owner_name": "Karl Prahl",
    "owner_persona": null,
    "category": "Poultry & Meat",
    "created_at": "2026-06-01",
    "transaction_count": 71,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "recUjkltTX3AaJpF0"
  },
  {
    "voucher_address": "0x0ed172b9579199a24015560370f42ebfdc7253c9",
    "symbol": "SGFG",
    "voucher_name": "Sarah's Gluten Free Goods",
    "voucher_description": "Gluten, dairy, nut, and corn free desserts and baked goods, and also offering Vegan treats as well. ",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "Granville Road, Westfield, MA 01085",
    "geo": {
      "x": 42.1204293,
      "y": -72.7777229
    },
    "voucher_email": "scollins0590@gmail.com",
    "voucher_website": "https://www.sarahsgfgoods.com/",
    "banner_url": "https://www.sarahsgfgoods.com/shop/p/product-2-5c6mb-j8mng-r6s6j-szxt4",
    "icon_url": "https://www.sarahsgfgoods.com/shop/p/product-2-5c6mb-j8mng-r6s6j-szxt4",
    "redemption_address": "0x0eb4d83d4b29df0294f72dc794d8bda20833ffe9",
    "owner_name": "Sarah",
    "owner_persona": null,
    "category": "Gluten Free Baked Goods",
    "created_at": "2026-06-06",
    "transaction_count": 343,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "recab2QXG8IIYcNuQ"
  },
  {
    "voucher_address": "0x62289103646d7d4993bb5f00bc4cfa5613411e7d",
    "symbol": "ZILCH",
    "voucher_name": "Zilch",
    "voucher_description": "As a zero-waste refillery, ZILCH will provide high quality, locally sourced, organic foods and goods near as net zero impact as possible. ZILCH is not  just a grocery store—it's a way of living .",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "Easthampton Farmers Market, MA",
    "geo": {
      "x": 42.27037,
      "y": -72.67196
    },
    "voucher_email": "aclark@zilchers.com",
    "voucher_website": "https://www.zilchers.com/",
    "banner_url": "https://images.squarespace-cdn.com/content/v1/635814470ac69042984fd89d/1728514687137-DJSH0JXJLOWFQH11XTGK/unsplash-image-wwTvwS9vKZs.jpg?format=1500w",
    "icon_url": "https://images.squarespace-cdn.com/content/v1/635814470ac69042984fd89d/1728514687137-DJSH0JXJLOWFQH11XTGK/unsplash-image-wwTvwS9vKZs.jpg?format=1500w",
    "redemption_address": "0xd8eff982a4742b628fb3c3a2bd0d77b5f5bc3f1a",
    "owner_name": "Amanda Loughrey",
    "owner_persona": null,
    "category": "Grocery",
    "created_at": "2026-06-06",
    "transaction_count": 328,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "recbfySUIQ0negQjt"
  },
  {
    "voucher_address": "0xb96822001c14c0160897e1b02d7a380598b8b7d9",
    "symbol": "PECKI",
    "voucher_name": "Peckish",
    "voucher_description": "Vegan & dairy free cakes, waffles, butter, milk and more",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "Easthampton Farmers Market, MA",
    "geo": {
      "x": 42.2665,
      "y": -72.6819
    },
    "voucher_email": "eatpeckish@gmail.com",
    "voucher_website": "www.eatpeckish.com",
    "banner_url": null,
    "icon_url": null,
    "redemption_address": "0xacb3c09eb557d24072761504caedc14c22451bc8",
    "owner_name": "Klay Kipler (they/he)",
    "owner_persona": null,
    "category": "Vegan & dairy free baked goods",
    "created_at": "2026-06-01",
    "transaction_count": 264,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "recfZOmGygZLEHKMk"
  },
  {
    "voucher_address": "0xd3257971ab98ba280d3a4076e223d226e518b0a4",
    "symbol": "CFBF",
    "voucher_name": "Cure For Boredom Farm",
    "voucher_description": "A small vegetable farm in Western Massachusetts. We grow food using organic practices guided by soil health, seasonality, and long-term care for the land.",
    "voucher_type": "GIFTABLE",
    "voucher_uoa": "USD",
    "voucher_value": 1,
    "location_name": "Cummington, Mass",
    "geo": {
      "x": 42.4607504,
      "y": -72.8937762
    },
    "voucher_email": "cureforboredomfarm@gmail.com",
    "voucher_website": "www.cureforboredomfarm.com",
    "banner_url": "https://images.squarespace-cdn.com/content/v1/6957cac8fb4a9065bd0145fc/1772661403538-QHD5J2Y5Q6M82CNEAVP0/image-asset.jpeg?format=2500w",
    "icon_url": "https://images.squarespace-cdn.com/content/v1/6957cac8fb4a9065bd0145fc/1772661403538-QHD5J2Y5Q6M82CNEAVP0/image-asset.jpeg?format=2500w",
    "redemption_address": "0x1ca3de8292579ada3d21d0137b51ef3094494e2e",
    "owner_name": "Hunt and Joy",
    "owner_persona": null,
    "category": "Vegetables",
    "created_at": "2026-06-01",
    "transaction_count": 203,
    "internal": false,
    "contract_version": "1.0",
    "airtable_id": "recvHtoQszERYKsyn"
  }
] as GeneratedVoucher[];

export type GeneratedOffer = {
  id: number;
  commodity_name: string;
  commodity_description: string;
  commodity_type: "GOOD";
  price: number;
  quantity: number;
  frequency: string;
  image_url: string;
  voucher_address: `0x${string}`;
  voucher_name: string;
  voucher_symbol: string;
  location_name: string;
  voucher_geo: { x: number; y: number };
};

export const AIRTABLE_EFM_OFFERS: GeneratedOffer[] = [
  {
    "id": 1001,
    "commodity_name": "Artisan Soap Bar",
    "commodity_description": "Handmade cold-process soap bar",
    "commodity_type": "GOOD",
    "price": 8,
    "quantity": 29,
    "frequency": "weekly",
    "image_url": "https://619b00c56e4d8981e886.cdn6.editmysite.com/uploads/b/619b00c56e4d8981e8864791695f16befbf7269cbc55678743ea48a58f666a8e/PXL_20251012_201915377.RAW-01.COVER%20%283%29_1773846515.jpg?width=2400&optimize=medium",
    "voucher_address": "0x5c79dd28eb25d86753a6bff1942e36b9d7dbe63a",
    "voucher_name": "Beyond Happiness",
    "voucher_symbol": "BH",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.26573,
      "y": -72.67318
    }
  },
  {
    "id": 1002,
    "commodity_name": "Body Butter",
    "commodity_description": "Whipped shea & cocoa body butter",
    "commodity_type": "GOOD",
    "price": 12,
    "quantity": 36,
    "frequency": "weekly",
    "image_url": "https://619b00c56e4d8981e886.cdn6.editmysite.com/uploads/b/619b00c56e4d8981e8864791695f16befbf7269cbc55678743ea48a58f666a8e/PXL_20251012_201915377.RAW-01.COVER%20%283%29_1773846515.jpg?width=2400&optimize=medium",
    "voucher_address": "0x5c79dd28eb25d86753a6bff1942e36b9d7dbe63a",
    "voucher_name": "Beyond Happiness",
    "voucher_symbol": "BH",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.26573,
      "y": -72.67318
    }
  },
  {
    "id": 1003,
    "commodity_name": "Incense Bundle",
    "commodity_description": "Hand-rolled incense sticks",
    "commodity_type": "GOOD",
    "price": 6,
    "quantity": 43,
    "frequency": "weekly",
    "image_url": "https://619b00c56e4d8981e886.cdn6.editmysite.com/uploads/b/619b00c56e4d8981e8864791695f16befbf7269cbc55678743ea48a58f666a8e/PXL_20251012_201915377.RAW-01.COVER%20%283%29_1773846515.jpg?width=2400&optimize=medium",
    "voucher_address": "0x5c79dd28eb25d86753a6bff1942e36b9d7dbe63a",
    "voucher_name": "Beyond Happiness",
    "voucher_symbol": "BH",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.26573,
      "y": -72.67318
    }
  },
  {
    "id": 1004,
    "commodity_name": "All-Purpose Surface Spray",
    "commodity_description": "Plant-based cleaning spray",
    "commodity_type": "GOOD",
    "price": 10,
    "quantity": 18,
    "frequency": "weekly",
    "image_url": "https://v5.airtableusercontent.com/v3/u/54/54/1780876800000/70Dvl7e-b2q4rsIlFtVKug/KfQNoH6VtGWgjYATx67B154PHStZ9-yo48CrBL3-RFIrOgjGmJk2JxhXh7bp2ayMMKSxHiuS-Mr4qFJ4eWxuTbixMCFeOXKmcplcCKdHmUveD6XQzxBpSyiZF5Eauq3ZEbRj8IQJFbTAi8YhqCFb8fskrDLS6_nGWMt0e6zb7EE/gkt83d9G7RcVDu97lQIFjFy21x37UwQgkNueoh6xtM0",
    "voucher_address": "0x83f5d9f2f34c40c4d562cb16630c5536024b874e",
    "voucher_name": "Hearth",
    "voucher_symbol": "HEART",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.26652,
      "y": -72.67789
    }
  },
  {
    "id": 1005,
    "commodity_name": "Room & Linen Mist",
    "commodity_description": "Botanical room mist",
    "commodity_type": "GOOD",
    "price": 9,
    "quantity": 25,
    "frequency": "weekly",
    "image_url": "https://v5.airtableusercontent.com/v3/u/54/54/1780876800000/70Dvl7e-b2q4rsIlFtVKug/KfQNoH6VtGWgjYATx67B154PHStZ9-yo48CrBL3-RFIrOgjGmJk2JxhXh7bp2ayMMKSxHiuS-Mr4qFJ4eWxuTbixMCFeOXKmcplcCKdHmUveD6XQzxBpSyiZF5Eauq3ZEbRj8IQJFbTAi8YhqCFb8fskrDLS6_nGWMt0e6zb7EE/gkt83d9G7RcVDu97lQIFjFy21x37UwQgkNueoh6xtM0",
    "voucher_address": "0x83f5d9f2f34c40c4d562cb16630c5536024b874e",
    "voucher_name": "Hearth",
    "voucher_symbol": "HEART",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.26652,
      "y": -72.67789
    }
  },
  {
    "id": 1006,
    "commodity_name": "All-Purpose Surface Spray",
    "commodity_description": "Plant-based cleaning spray",
    "commodity_type": "GOOD",
    "price": 10,
    "quantity": 39,
    "frequency": "weekly",
    "image_url": "https://davesnaturalgarden.com/wp-content/uploads/2022/06/Screen-Shot-2022-05-23-at-9.23.29-AM.png",
    "voucher_address": "0xa8017dc1391c720cd9f563efa166cbe1e11a5845",
    "voucher_name": "Dave's Natural Garden Farm",
    "voucher_symbol": "DNGF",
    "location_name": "35 Amherst Street Granby, MA, 01033",
    "voucher_geo": {
      "x": 42.2518026,
      "y": -72.5425728
    }
  },
  {
    "id": 1007,
    "commodity_name": "Room & Linen Mist",
    "commodity_description": "Botanical room mist",
    "commodity_type": "GOOD",
    "price": 9,
    "quantity": 46,
    "frequency": "weekly",
    "image_url": "https://davesnaturalgarden.com/wp-content/uploads/2022/06/Screen-Shot-2022-05-23-at-9.23.29-AM.png",
    "voucher_address": "0xa8017dc1391c720cd9f563efa166cbe1e11a5845",
    "voucher_name": "Dave's Natural Garden Farm",
    "voucher_symbol": "DNGF",
    "location_name": "35 Amherst Street Granby, MA, 01033",
    "voucher_geo": {
      "x": 42.2518026,
      "y": -72.5425728
    }
  },
  {
    "id": 1008,
    "commodity_name": "Pasture Ground Beef",
    "commodity_description": "Grass-fed ground beef (1 lb)",
    "commodity_type": "GOOD",
    "price": 11,
    "quantity": 18,
    "frequency": "weekly",
    "image_url": "https://davesnaturalgarden.com/wp-content/uploads/2022/06/Screen-Shot-2022-05-23-at-9.23.29-AM.png",
    "voucher_address": "0xa8017dc1391c720cd9f563efa166cbe1e11a5845",
    "voucher_name": "Dave's Natural Garden Farm",
    "voucher_symbol": "DNGF",
    "location_name": "35 Amherst Street Granby, MA, 01033",
    "voucher_geo": {
      "x": 42.2518026,
      "y": -72.5425728
    }
  },
  {
    "id": 1009,
    "commodity_name": "Layer Cake Slice",
    "commodity_description": "Generous slice of the week's layer cake",
    "commodity_type": "GOOD",
    "price": 7,
    "quantity": 32,
    "frequency": "weekly",
    "image_url": "https://static.wixstatic.com/media/d1bc48_2f91000d216a49c694dbeffb39cac652~mv2.jpg/v1/fill/w_857,h_1024,al_c,q_85,enc_avif,quality_auto/d1bc48_2f91000d216a49c694dbeffb39cac652~mv2.jpg",
    "voucher_address": "0xc3bba0a8314a84b0c7d95ebd9f714aab3d1a2b69",
    "voucher_name": "Sweetly By Leila",
    "voucher_symbol": "SBL",
    "location_name": "Easthampton, MA",
    "voucher_geo": {
      "x": 42.2708804,
      "y": -72.6719579
    }
  },
  {
    "id": 1010,
    "commodity_name": "Cupcake 4-Pack",
    "commodity_description": "Assorted from-scratch cupcakes",
    "commodity_type": "GOOD",
    "price": 12,
    "quantity": 39,
    "frequency": "weekly",
    "image_url": "https://static.wixstatic.com/media/d1bc48_2f91000d216a49c694dbeffb39cac652~mv2.jpg/v1/fill/w_857,h_1024,al_c,q_85,enc_avif,quality_auto/d1bc48_2f91000d216a49c694dbeffb39cac652~mv2.jpg",
    "voucher_address": "0xc3bba0a8314a84b0c7d95ebd9f714aab3d1a2b69",
    "voucher_name": "Sweetly By Leila",
    "voucher_symbol": "SBL",
    "location_name": "Easthampton, MA",
    "voucher_geo": {
      "x": 42.2708804,
      "y": -72.6719579
    }
  },
  {
    "id": 1011,
    "commodity_name": "Chicken & Sausage Gumbo",
    "commodity_description": "Hearty pint of classic gumbo",
    "commodity_type": "GOOD",
    "price": 14,
    "quantity": 32,
    "frequency": "weekly",
    "image_url": "https://v5.airtableusercontent.com/v3/u/54/54/1780876800000/jUdafcdimWdhoULwQgGEjw/JWhKIp6zwpppPEOxExJLtI2QxbSD9AkRBmj1nVD8dqGr7HauEqDzkTtqUfIc4OHySAFw7VLohNvXD3lBdh0ABNWuhaYhdbW22TPJW4POrdP4ynZ0kX5uq5BiNYLYOyuwwEhLAU2BsX5MNsAwJEwmBjr3QbsOPH9akqbvCgBqnbs/nX22Nz3A6D3r5UjlVZOsWHi0npSkOXYhAs2a-oJFUxY",
    "voucher_address": "0xc542c74562819c35961b41492029773552d31ff6",
    "voucher_name": "Sid's Gumbo Pot",
    "voucher_symbol": "SGP",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.27289,
      "y": -72.6793
    }
  },
  {
    "id": 1012,
    "commodity_name": "Red Beans & Rice",
    "commodity_description": "Slow-cooked red beans over rice",
    "commodity_type": "GOOD",
    "price": 10,
    "quantity": 39,
    "frequency": "weekly",
    "image_url": "https://v5.airtableusercontent.com/v3/u/54/54/1780876800000/jUdafcdimWdhoULwQgGEjw/JWhKIp6zwpppPEOxExJLtI2QxbSD9AkRBmj1nVD8dqGr7HauEqDzkTtqUfIc4OHySAFw7VLohNvXD3lBdh0ABNWuhaYhdbW22TPJW4POrdP4ynZ0kX5uq5BiNYLYOyuwwEhLAU2BsX5MNsAwJEwmBjr3QbsOPH9akqbvCgBqnbs/nX22Nz3A6D3r5UjlVZOsWHi0npSkOXYhAs2a-oJFUxY",
    "voucher_address": "0xc542c74562819c35961b41492029773552d31ff6",
    "voucher_name": "Sid's Gumbo Pot",
    "voucher_symbol": "SGP",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.27289,
      "y": -72.6793
    }
  },
  {
    "id": 1013,
    "commodity_name": "Pasture Ground Beef",
    "commodity_description": "Grass-fed ground beef (1 lb)",
    "commodity_type": "GOOD",
    "price": 11,
    "quantity": 27,
    "frequency": "weekly",
    "image_url": "https://www.underlinefarm.com/gallery?pgid=jjz2uhq6-37ef36ad-a7f6-4b36-abcc-f37d20ae8643",
    "voucher_address": "0x314decfef49f87d5fee4ca2e53f9177cabf7fa5c",
    "voucher_name": "Underline Farm",
    "voucher_symbol": "UF",
    "location_name": "P.O. Box 413, Easthampton, MA 01027",
    "voucher_geo": {
      "x": 42.26791,
      "y": -72.66506
    }
  },
  {
    "id": 1014,
    "commodity_name": "Heritage Pork Chops",
    "commodity_description": "Pasture-raised pork chops",
    "commodity_type": "GOOD",
    "price": 14,
    "quantity": 34,
    "frequency": "weekly",
    "image_url": "https://www.underlinefarm.com/gallery?pgid=jjz2uhq6-37ef36ad-a7f6-4b36-abcc-f37d20ae8643",
    "voucher_address": "0x314decfef49f87d5fee4ca2e53f9177cabf7fa5c",
    "voucher_name": "Underline Farm",
    "voucher_symbol": "UF",
    "location_name": "P.O. Box 413, Easthampton, MA 01027",
    "voucher_geo": {
      "x": 42.26791,
      "y": -72.66506
    }
  },
  {
    "id": 1015,
    "commodity_name": "Whole Chicken",
    "commodity_description": "Pasture-raised whole chicken",
    "commodity_type": "GOOD",
    "price": 20,
    "quantity": 41,
    "frequency": "weekly",
    "image_url": "https://www.underlinefarm.com/gallery?pgid=jjz2uhq6-37ef36ad-a7f6-4b36-abcc-f37d20ae8643",
    "voucher_address": "0x314decfef49f87d5fee4ca2e53f9177cabf7fa5c",
    "voucher_name": "Underline Farm",
    "voucher_symbol": "UF",
    "location_name": "P.O. Box 413, Easthampton, MA 01027",
    "voucher_geo": {
      "x": 42.26791,
      "y": -72.66506
    }
  },
  {
    "id": 1016,
    "commodity_name": "Layer Cake Slice",
    "commodity_description": "Generous slice of the week's layer cake",
    "commodity_type": "GOOD",
    "price": 7,
    "quantity": 27,
    "frequency": "weekly",
    "image_url": "https://www.sarahsgfgoods.com/shop/p/product-2-5c6mb-j8mng-r6s6j-szxt4",
    "voucher_address": "0x0ed172b9579199a24015560370f42ebfdc7253c9",
    "voucher_name": "Sarah's Gluten Free Goods",
    "voucher_symbol": "SGFG",
    "location_name": "Granville Road, Westfield, MA 01085",
    "voucher_geo": {
      "x": 42.1204293,
      "y": -72.7777229
    }
  },
  {
    "id": 1017,
    "commodity_name": "Cupcake 4-Pack",
    "commodity_description": "Assorted from-scratch cupcakes",
    "commodity_type": "GOOD",
    "price": 12,
    "quantity": 34,
    "frequency": "weekly",
    "image_url": "https://www.sarahsgfgoods.com/shop/p/product-2-5c6mb-j8mng-r6s6j-szxt4",
    "voucher_address": "0x0ed172b9579199a24015560370f42ebfdc7253c9",
    "voucher_name": "Sarah's Gluten Free Goods",
    "voucher_symbol": "SGFG",
    "location_name": "Granville Road, Westfield, MA 01085",
    "voucher_geo": {
      "x": 42.1204293,
      "y": -72.7777229
    }
  },
  {
    "id": 1018,
    "commodity_name": "GF Sandwich Bread",
    "commodity_description": "Soft gluten-free sandwich loaf",
    "commodity_type": "GOOD",
    "price": 9,
    "quantity": 41,
    "frequency": "weekly",
    "image_url": "https://www.sarahsgfgoods.com/shop/p/product-2-5c6mb-j8mng-r6s6j-szxt4",
    "voucher_address": "0x0ed172b9579199a24015560370f42ebfdc7253c9",
    "voucher_name": "Sarah's Gluten Free Goods",
    "voucher_symbol": "SGFG",
    "location_name": "Granville Road, Westfield, MA 01085",
    "voucher_geo": {
      "x": 42.1204293,
      "y": -72.7777229
    }
  },
  {
    "id": 1019,
    "commodity_name": "Pantry Staples Box",
    "commodity_description": "Curated box of local pantry goods",
    "commodity_type": "GOOD",
    "price": 25,
    "quantity": 33,
    "frequency": "weekly",
    "image_url": "https://images.squarespace-cdn.com/content/v1/635814470ac69042984fd89d/1728514687137-DJSH0JXJLOWFQH11XTGK/unsplash-image-wwTvwS9vKZs.jpg?format=1500w",
    "voucher_address": "0x62289103646d7d4993bb5f00bc4cfa5613411e7d",
    "voucher_name": "Zilch",
    "voucher_symbol": "ZILCH",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.27037,
      "y": -72.67196
    }
  },
  {
    "id": 1020,
    "commodity_name": "Bulk Refill Credit",
    "commodity_description": "Refill credit toward bulk goods",
    "commodity_type": "GOOD",
    "price": 10,
    "quantity": 40,
    "frequency": "weekly",
    "image_url": "https://images.squarespace-cdn.com/content/v1/635814470ac69042984fd89d/1728514687137-DJSH0JXJLOWFQH11XTGK/unsplash-image-wwTvwS9vKZs.jpg?format=1500w",
    "voucher_address": "0x62289103646d7d4993bb5f00bc4cfa5613411e7d",
    "voucher_name": "Zilch",
    "voucher_symbol": "ZILCH",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.27037,
      "y": -72.67196
    }
  },
  {
    "id": 1021,
    "commodity_name": "Layer Cake Slice",
    "commodity_description": "Generous slice of the week's layer cake",
    "commodity_type": "GOOD",
    "price": 7,
    "quantity": 23,
    "frequency": "weekly",
    "image_url": "https://picsum.photos/seed/818/400/300",
    "voucher_address": "0xb96822001c14c0160897e1b02d7a380598b8b7d9",
    "voucher_name": "Peckish",
    "voucher_symbol": "PECKI",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.2665,
      "y": -72.6819
    }
  },
  {
    "id": 1022,
    "commodity_name": "Cupcake 4-Pack",
    "commodity_description": "Assorted from-scratch cupcakes",
    "commodity_type": "GOOD",
    "price": 12,
    "quantity": 30,
    "frequency": "weekly",
    "image_url": "https://picsum.photos/seed/819/400/300",
    "voucher_address": "0xb96822001c14c0160897e1b02d7a380598b8b7d9",
    "voucher_name": "Peckish",
    "voucher_symbol": "PECKI",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.2665,
      "y": -72.6819
    }
  },
  {
    "id": 1023,
    "commodity_name": "Vegan Brownie",
    "commodity_description": "Fudgy dairy-free brownie",
    "commodity_type": "GOOD",
    "price": 5,
    "quantity": 37,
    "frequency": "weekly",
    "image_url": "https://picsum.photos/seed/820/400/300",
    "voucher_address": "0xb96822001c14c0160897e1b02d7a380598b8b7d9",
    "voucher_name": "Peckish",
    "voucher_symbol": "PECKI",
    "location_name": "Easthampton Farmers Market, MA",
    "voucher_geo": {
      "x": 42.2665,
      "y": -72.6819
    }
  },
  {
    "id": 1024,
    "commodity_name": "Mixed Veggie Box",
    "commodity_description": "Seasonal CSA-style vegetable box",
    "commodity_type": "GOOD",
    "price": 22,
    "quantity": 34,
    "frequency": "weekly",
    "image_url": "https://images.squarespace-cdn.com/content/v1/6957cac8fb4a9065bd0145fc/1772661403538-QHD5J2Y5Q6M82CNEAVP0/image-asset.jpeg?format=2500w",
    "voucher_address": "0xd3257971ab98ba280d3a4076e223d226e518b0a4",
    "voucher_name": "Cure For Boredom Farm",
    "voucher_symbol": "CFBF",
    "location_name": "Cummington, Mass",
    "voucher_geo": {
      "x": 42.4607504,
      "y": -72.8937762
    }
  },
  {
    "id": 1025,
    "commodity_name": "Salad Greens",
    "commodity_description": "Washed mixed salad greens",
    "commodity_type": "GOOD",
    "price": 5,
    "quantity": 41,
    "frequency": "weekly",
    "image_url": "https://images.squarespace-cdn.com/content/v1/6957cac8fb4a9065bd0145fc/1772661403538-QHD5J2Y5Q6M82CNEAVP0/image-asset.jpeg?format=2500w",
    "voucher_address": "0xd3257971ab98ba280d3a4076e223d226e518b0a4",
    "voucher_name": "Cure For Boredom Farm",
    "voucher_symbol": "CFBF",
    "location_name": "Cummington, Mass",
    "voucher_geo": {
      "x": 42.4607504,
      "y": -72.8937762
    }
  },
  {
    "id": 1026,
    "commodity_name": "Seasonal Bunch",
    "commodity_description": "This week's featured vegetable",
    "commodity_type": "GOOD",
    "price": 4,
    "quantity": 48,
    "frequency": "weekly",
    "image_url": "https://images.squarespace-cdn.com/content/v1/6957cac8fb4a9065bd0145fc/1772661403538-QHD5J2Y5Q6M82CNEAVP0/image-asset.jpeg?format=2500w",
    "voucher_address": "0xd3257971ab98ba280d3a4076e223d226e518b0a4",
    "voucher_name": "Cure For Boredom Farm",
    "voucher_symbol": "CFBF",
    "location_name": "Cummington, Mass",
    "voucher_geo": {
      "x": 42.4607504,
      "y": -72.8937762
    }
  }
] as GeneratedOffer[];
